
variables:
  DOCKER_DRIVER: overlay
  VERSION: 1.0.1

image: docker:git

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

.job_template: &build_app
  stage: build
  image: golang:1.8
  artifacts:
    expire_in: 2 hrs
    paths:
      - linux_arm/kube-state-metrics
  script:
    - git clone https://github.com/kubernetes/kube-state-metrics $GOPATH/src/k8s.io/kube-state-metrics
    - cd $GOPATH/src/k8s.io/kube-state-metrics
    - git checkout v${VERSION}
    - ls

development:
  stage: deploy
  <<: *build_app
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:latest" 1.0
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

testing:
  stage: deploy
  <<: *build_app
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}" 1.0
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}"
  only:
    - branches
  except:
    - master

stable:
  stage: deploy
  <<: *build_app
  script:
    - export VERSION=$(grep ' VERSION' 1.0/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker build -t "$CI_REGISTRY_IMAGE:v${VERSION}" 1.0
    - docker push "$CI_REGISTRY_IMAGE:v${VERSION}"
  only:
    - tags
