
variables:
  DOCKER_DRIVER: overlay
  VERSION: 1.1.0

image: docker:git

services:
  - docker:dind

stages:
  - compile
  - build
  - release

compile:app:
  stage: compile
  image: golang:1.9
  script:
    - git clone https://github.com/kubernetes/kube-state-metrics $GOPATH/src/k8s.io/kube-state-metrics
    - cd $GOPATH/src/k8s.io/kube-state-metrics
    - git checkout v${VERSION}
    - go get github.com/tools/godep
    - GOARCH=arm make build
    - ls -al
    - cp kube-state-metrics ${CI_PROJECT_DIR}/
  artifacts:
    when: on_success
    expire_in: 1 day 
    paths:
      - kube-state-metrics

build:master:
  stage: build
  dependencies:
    - compile:app
  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - ls
    - cp kube-state-metrics 1.1/kube-state-metrics
    - docker build -t "$CI_REGISTRY_IMAGE:latest" 1.1
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

build:branch:
  stage: build
  dependencies:
    - compile:app
  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - cp kube-state-metrics 1.1/kube-state-metrics
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}" 1.1
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}"
  only:
    - branches
  except:
    - master

release:master:
  stage: release
  dependencies:
    - compile:app
  script:
    - export VERSION=$(grep ' VERSION' 1.1/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - cp kube-state-metrics 1.1/kube-state-metrics
    - docker build -t "$CI_REGISTRY_IMAGE:v${VERSION}" 1.1
    - docker push "$CI_REGISTRY_IMAGE:v${VERSION}"
  only:
    - tags

