sudo: required
services:
  - docker
language: bash
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t zeiot/rpi-kube-state-metrics:1.0 1.0
  - docker run zeiot/rpi-kube-state-metrics:1.0 --version
